absblog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
# from . import views
from .views import *


urlpatterns = [
    # path('', views.home, name="home"),
    path('', HomeView.as_view(), name="home"),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article-detail'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('pending-posts/', pendingPosts, name='pending-posts'),
    path('my-posts/', myPosts, name='my-posts'),
    path('add-reason/', AddReason, name='add-reason'),
    path('activate-post/<int:pk>', activatePost, name='activate-post'),
    path('manage-users/', ManageUsers, name='manage-users'),
    path('edit-user/<int:pk>', EditUserAndProfileView.as_view(), name='edit-user'),
    path('account/reset-password/<str:email>',
         resetPassword, name='reset-password'),
    path('remove-user/<int:pk>', RemoveUser, name='remove-user'),
    path('add-user/', AddUserView.as_view(), name='add-user'),
    path('add-tag/', AddTags, name='add-tag'),
    path('delete-tag', DeleteTag, name='delete-tag'),
    path('add_category/', AddCategoryView.as_view(), name='add_category'),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name='update_post'),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name='delete_post'),
    path('category/<str:cats>/', CategoryView, name='category'),
    path('category-list/', CategoryListView, name='category-list'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('article/<int:pk>/comment/',
         AddCommentView.as_view(), name='add_comment'),
    path('edit-comment/<int:pk>/', editComment, name='edit-comment'),
    path('hide-comment/<int:pk>/', hideComment, name='hide-comment'),
    path('update-comment/<int:pk>/', updateComment, name='update-comment'),

]

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post, Category, Comment, Profile

choices = Category.objects.all().values_list('name', 'name')

choice_list = []

for item in choices:
    choice_list.append(item)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'title_tag', 'author',
                  'category', 'body', 'snippet')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'user', 'type': 'hidden'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control'}),

        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'title_tag', 'body', 'snippet')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
            # 'author': forms.Select(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control'}),

        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'profile_pic', 'role', 'website_url',
                  'facebook_url', 'twitter_url', 'instagram_url', 'pinterest_url']
        widgets = {
            'website_url': forms.TextInput(attrs={'class': 'form-control'}),
            'facebook_url': forms.TextInput(attrs={'class': 'form-control'}),
            'twitter_url': forms.TextInput(attrs={'class': 'form-control'}),
            'instagram_url': forms.TextInput(attrs={'class': 'form-control'}),
            'pinterest_url': forms.TextInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control'}),
        }
    role = forms.ChoiceField(
        choices=Profile.Role.choices,
        widget=forms.RadioSelect
    )
    profile_pic = forms.FileField(label='Profile Picture')


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'role', 'website_url',
                  'facebook_url', 'twitter_url', 'instagram_url', 'pinterest_url']
        widgets = {
            'website_url': forms.TextInput(attrs={'class': 'form-control'}),
            'facebook_url': forms.TextInput(attrs={'class': 'form-control'}),
            'twitter_url': forms.TextInput(attrs={'class': 'form-control'}),
            'instagram_url': forms.TextInput(attrs={'class': 'form-control'}),
            'pinterest_url': forms.TextInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control'}),
        }
    role = forms.ChoiceField(
        choices=Profile.Role.choices,
        widget=forms.RadioSelect
    )
class ResetPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

blog/views.py
from django.contrib.auth.hashers import make_password
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category, Comment, Profile, Tag, RejectionReason
from .forms import PostForm, EditForm, CommentForm, UserForm, ProfileForm, ResetPasswordForm, EditUserForm, EditProfileForm
from django.urls import reverse_lazy, reverse, resolve
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.views import View
from .utils import sendEmail
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json

# def home(request):
#    return render(request, 'home.html', {})


def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True

    return HttpResponseRedirect(reverse('article-detail', args=[str(pk)]))


class HomeView(ListView):
    model = Post
    template_name = 'home.html'
    ordering = ['-post_date']
    # order posts by primary key in reverse order
    # ordering = ['-id']

    def get_queryset(self):
        return super().get_queryset().filter(approved=True)

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context

# function method in lieu of class method


def CategoryListView(request):
    cat_menu_list = Category.objects.all()
    return render(request, 'category_list.html', {'cat_menu_list': cat_menu_list})


def CategoryView(request, cats):
    category_posts = Post.objects.filter(
        category__icontains=cats.replace('-', ' '), approved=True)
    return render(request, 'categories.html', {'cats': cats.title().replace('-', ' '), 'category_posts': category_posts})


class ArticleDetailView(DetailView):
    model = Post
    template_name = 'article_details.html'

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(ArticleDetailView, self).get_context_data(
            *args, **kwargs)

        stuff = get_object_or_404(Post, id=self.kwargs['pk'])
        total_likes = stuff.total_likes()

        liked = False
        if stuff.likes.filter(id=self.request.user.id).exists():
            liked = True

        context["cat_menu"] = cat_menu
        context['total_likes'] = total_likes
        context['liked'] = liked
        return context

class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'
    # fields = '__all__'
    # fields = ('title', 'body')

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(AddPostView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user
        if not hasattr(user, "profile") or user.profile.role == 'end_user':
            form.fields.pop('snippet')
            form.fields.pop('category')
            form.fields.pop('title_tag')
        return form


def pendingPosts(request):
    posts = Post.objects.filter(approved=False)
    return render(request, "pending-posts.html", {"posts": posts})


def myPosts(request):
    posts = Post.objects.filter(author_id=request.user.id)
    return render(request, "my-posts.html", {"posts": posts})


def activatePost(request, pk):
    post = Post.objects.get(id=pk)
    if post:
        post.approved = True
        post.save()
        return redirect("pending-posts")
    return redirect("pending-posts")

def AddReason(request):
    post_id = request.POST.get("post_id")
    reason = request.POST.get("reason")
    reason_obj = RejectionReason.objects.create(post_id=post_id, reason=reason)
    reason_obj.save()
    messages.success(request, 'Reason Added Successfully!')
    return redirect("pending-posts")
    


class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'add_comment.html'
    success_url = reverse_lazy('home')
    # fields = '__all__'

    # Figure out which user is using this form and then continue processing.
    # Look back at the page that is using Javascript and replace with this method.

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        form.instance.user = self.request.user
        return super().form_valid(form)


def editComment(request, pk):
    comment = Comment.objects.get(id=pk)
    if comment:
        return render(request, "edit-comment.html", {"comment": comment})
    messages.error(request, 'No Comment Found!')
    return redirect(request.META.get('HTTP_REFERER'))

def updateComment(request, pk):
    name = request.POST.get("name")
    body = request.POST.get("body")
    comment = Comment.objects.get(id=pk)
    if comment:
        comment.name = name
        comment.body = body
        comment.save()
        return redirect("article-detail/"+comment.post_id)
        
    messages.error(request, 'No Comment Found!')
    return redirect(request.META.get('HTTP_REFERER'))

def hideComment(request, pk):
    comment = Comment.objects.get(id=pk)
    comment.hidden = True
    comment.save()
    if comment:
        return redirect(request.META.get('HTTP_REFERER'))
    messages.error(request, 'No Comment Found!')
   

class AddCategoryView(CreateView):
    model = Category
    # form_class = PostForm
    template_name = 'add_category.html'
    fields = '__all__'
    # fields = ('title', 'body')

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(AddCategoryView, self).get_context_data(
            *args, **kwargs)
        context["cat_menu"] = cat_menu
        return context


class UpdatePostView(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'update_post.html'
    # fields = ['title', 'title_tag', 'body']

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(UpdatePostView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context


class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(DeletePostView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context


def ManageUsers(request):
    users = User.objects.filter(
        is_active=True, is_superuser=False).select_related('profile').all()
    return render(request, "manage_users.html", {"users": users})


def RemoveUser(request, pk):
    user = User.objects.get(id=pk)
    user.is_active = False
    user.save()
    return redirect("/manage-users")


def resetPassword(request, email):
    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        email = request.POST.get("email")
        if form.is_valid():
            password = form.cleaned_data['password']

            # Set the new password for the user
            # Code for setting the password goes here
            user = User.objects.filter(email=email).first()
            if user:
                user.password = make_password(password)
                user.save()
            messages.success(request, 'Password has been reset successfully.')
            return redirect('login')
        else:
            messages.error(request, 'Passwords do not match!')
            form = ResetPasswordForm(initial={'email': email})
    else:
        messages.error(request, 'Passwords are required!')
        form = ResetPasswordForm(initial={'email': email})

    return render(request, 'reset-pass.html', {'form': form, 'email': email})


class AddUserView(View):
    def get(self, request):
        user_form = UserForm()
        profile_form = ProfileForm()
        return render(request, 'add_user.html', {'user_form': user_form, 'profile_form': profile_form})

    def post(self, request):
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)
        role = request.POST.get("role")

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.is_staff = True
            user.password = make_password(user_form.cleaned_data['password'])
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            # Send email to the newly added user
            sendEmail(user, profile, user_form.cleaned_data['password'])
            return redirect('manage-users')

        return render(request, 'add_user.html', {'user_form': user_form, 'profile_form': profile_form})


class EditUserAndProfileView(View):
    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        profileExists = Profile.objects.filter(user_id=user.pk).first()
        if not profileExists:
            profile = Profile.objects.create(user=user, role="end_user").save()
        else:
            profile = get_object_or_404(Profile, user=user)
            
        user_form = EditUserForm(instance=user)
        profile_form = EditProfileForm(instance=profile)
        return render(request, 'edit_user.html', {'user_form': user_form, 'profile_form': profile_form})

    def post(self, request, pk):

blog/templates/add_category.html
{% extends 'base.html' %}
{% block title %}Create a new blog category{% endblock %}
{% block content %}

    <H1>Add Category</H1>
    <br/><br/>
    <div class="form-group">
        <form method=POST>
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-secondary">Add Category</button>
        </form>
    </div>

{% endblock %}

blog/templates/add_comment.html
{% extends 'base.html' %}
{% block title %}Comment on blog post{% endblock %}
{% block content %}

{% if user.is_authenticated %}
    <H1>Add Comment</H1>
    <br/><br/>
    <div class="form-group">
        <form method=POST>
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-secondary">Add Comment</button>
        </form>
    </div>
{% else %}

    You are not logged in so access to this page is limited.
    
{% endif %}

{% endblock %}

blog/templates/add_post.html
{% extends 'base.html' %}
{% block title %}Create a new blog post{% endblock %}
{% block content %}

    <H1>Add Post</H1>
    <br/><br/>
    <div class="form-group">
        <form method=POST enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="btn btn-secondary">Post</button>
        </form>
    </div>
    <br/>
    <script>
        var name = "{{ user.id }}";
        document.getElementById("user").value = name;
    </script>

{% endblock %}

blog/templates/add_user.html
{% extends 'base.html' %} 
{% block title %}Create new User {%endblock%} 
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
          <h1>Add New User</h1>
        </div>
        <div class="col-md-3"></div>
            <div class="col-md-8">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <!-- User Form Fields -->
                    <div>
                      <label for="{{ user_form.username.id_for_label }}">Username:</label>
                      {{ user_form.username }}
                      {% if user_form.username.errors %}
                        <ul class="errorlist">
                          {% for error in user_form.username.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                      {% endif %}
                    </div>
                    <div>
                        <label for="{{ user_form.first_name.id_for_label }}">first_name:</label>
                        {{ user_form.first_name }}
                        {% if user_form.first_name.errors %}
                          <ul class="errorlist">
                            {% for error in user_form.first_name.errors %}
                              <li>{{ error }}</li>
                            {% endfor %}
                          </ul>
                        {% endif %}
                      </div>
                      <div>
                        <label for="{{ user_form.last_name.id_for_label }}">last_name:</label>
                        {{ user_form.last_name }}
                        {% if user_form.last_name.errors %}
                          <ul class="errorlist">
                            {% for error in user_form.last_name.errors %}
                              <li>{{ error }}</li>
                            {% endfor %}
                          </ul>
                        {% endif %}
                      </div>
                    <div>
                      <label for="{{ user_form.password.id_for_label }}">Password:</label>
                      {{ user_form.password }}
                      {% if user_form.password.errors %}
                        <ul class="errorlist">
                          {% for error in user_form.password.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                      {% endif %}
                    </div>
                    <div>
                      <label for="{{ user_form.email.id_for_label }}">Email:</label>
                      {{ user_form.email }}
                      {% if user_form.email.errors %}
                        <ul class="errorlist">
                          {% for error in user_form.email.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                      {% endif %}
                    </div>
                  
                    <!-- Profile Form Fields -->
                    <div>
                      <label for="{{ profile_form.bio.id_for_label }}">Bio:</label>
                      {{ profile_form.bio }}
                      {% if profile_form.bio.errors %}
                        <ul class="errorlist">
                          {% for error in profile_form.bio.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                      {% endif %}
                    </div>
                    <div>
                      <label for="{{ profile_form.profile_pic.id_for_label }}">Profile Picture:</label>
                      {{ profile_form.profile_pic }}
                      {% if profile_form.profile_pic.errors %}
                        <ul class="errorlist">
                          {% for error in profile_form.profile_pic.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                      {% endif %}
                    </div>
                    <div>
                      <label for="{{ profile_form.role.id_for_label }}">Role:</label>
                      {{ profile_form.role }}
                      {% if profile_form.role.errors %}
                        <ul class="errorlist">
                          {% for error in profile_form.role.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                      {% endif %}
                    </div>
                    <div>
                      <label for="{{ profile_form.website_url.id_for_label }}">Website URL:</label>
                      {{ profile_form.website_url }}
                      {% if profile_form.website_url.errors %}
                        <ul class="errorlist">
                          {% for error in profile_form.website_url.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                      {% endif %}
                    </div>
                    <div>
                      <label for="{{ profile_form.facebook_url.id_for_label }}">Facebook URL:</label>
                      {{ profile_form.facebook_url }}
                      {% if profile_form.facebook_url.errors %}
                        <ul class="errorlist">
                          {% for error in profile_form.facebook_url.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                      {% endif %}
                    </div>
                    <div>
                      <label for="{{ profile_form.twitter_url.id_for_label }}">Twitter URL:</label>
                      {{ profile_form.twitter_url }}
                      {% if profile_form.twitter_url.errors %}
                        <ul class="errorlist">
                          {% for error in profile_form.twitter_url.errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        </ul>
                      {% endif %}
                    </div>
                    <div>
                        <button class="btn btn-info btn-block">Submit </button>
                      </div>
                </form>
                  
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/article_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ post.title_tag }}
{% endblock %}

{% block content %}

<h1>{{ post.title }}</h1>
<small>By: 
    {{ post.author.first_name }} 
    {{ post.author.last_name }} - 
    {{ post.post_date }}
    
    {% if user.profile.role == "moderator" or user.is_superuser == True or user.id == post.author.id %}
            - <a href="{% url 'update_post' post.pk %}">(Edit)</a>
            <a href="{% url 'delete_post' post.pk %}" style="color: red">(Delete)</a>
    {% endif %}
</small><br/>
<hr>
<br/>
{{ post.body|safe }}

<br/>
<br/>
<hr>
<br/>
<form action="{% url 'like_post' post.pk %}" method="POST">
    {% csrf_token %}
{% if user.is_authenticated %}
    {% if liked %}
        <button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-danger btn-sm">Unlike</button> 
    {% else %}
        <button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-primary btn-sm">Like</button> 
    {% endif %}
{% else %}
<small><a href="{% url 'login' %}">Log in</a> to like</small>
{% endif %}

    - {{ total_likes }} Likes
</form>
<br/>
<div class="card mb-3" style="background-color:#404040; color:#f2f2f2;">
    <div class="row g-0">
      <div class="col-md-2">
    {% if post.author.profile.profile_pic %}
        <img src="{{ post.author.profile.profile_pic.url }}" width="200" height="200">
    {% else %}
        <img src="{% static 'blog/images/default_profile_pic.png' %}" width="200" height="200">
    {% endif %}
      </div>
      <div class="col-md-10 px-2">
        <div class="card-body">
          <h5 class="card-title d-flex">
              {{ post.author.first_name }} 
              {{ post.author.last_name }}

              {% if post.author.profile.role == "scholar" %}
              <div class="d-flex p-1 mx-2">
                {% for tag in post.author.profile.tags.all %}
                  <code class="text-info bg-gradient"> <span class="mx-1">{{ tag.name }} </span> </code>
                {% endfor %}
              </div>
              {% endif %}
          </h5>
         
          <p class="small text-muted">
              {% if post.author.profile.id and post.author.profile.role != "end_user" %}
                  <a href="{% url 'show_profile_page' post.author.id %}">Profile Page</a>
              {% endif %}
              {% if post.author.profile.website_url %}
                | <a href="{{ post.author.profile.website_url }}">Website</a>
              {% endif %}
              {% if post.author.profile.facebook_url %}
                | <a href="{{ post.author.profile.facebook_url }}">Facebook</a>
              {% endif %}
              {% if post.author.profile.twitter_url %}
                | <a href="{{ post.author.profile.twitter_url }}">Twitter</a>
              {% endif %}
              {% if post.author.profile.instagram_url %}
                | <a href="{{ post.author.profile.instagram_url }}">Instagram</a>
              {% endif %}
              {% if post.author.profile.pinterest_url %}
                | <a href="{{ post.author.profile.pinterest_url }}">Pinterest</a>
              {% endif %}
           </p>
          <p class="card-text">{{ post.author.profile.bio }}</p>
        </div>
      </div>
    </div>
  </div>
<br/>
<h2>Comments</h2>
<br/>
{% if not post.comments.all %}

  {% if user.profile.role != "end_user" %}
    No comments yet...<a href="{% url 'add_comment' post.pk %}">Add one</a>
  {% endif %}
{% else %}
<a href="{% url 'add_comment' post.pk %}">Add comment</a>
  {% for comment in post.comments.all %}
    {% if not comment.hidden %}
      <strong class="d-flex ">
        {{ comment.user.first_name }} {{ comment.user.last_name }} 

        {% comment %} Adding tags in front of name {% endcomment %}
        {% if comment.user.profile.tags.count > 0 and comment.user.profile.role == "scholar" %}
        <div class="mx-2">
          {% for tag in comment.user.profile.tags.all %}
            <code class="text-info bg-gradient"> {{ tag.name }}|  </code>
          {% endfor %}
        </div>
        {% endif %}
        
        -
        {{ comment.date_added }}
      </strong>
      <br/>
        {{ comment.body }}
        {% if user.profile.role == "moderator" or user.is_superuser %}
          <a href="{% url 'hide-comment' comment.pk %}" style="color: red">(Hide)</a>
          {% if user.id == comment.user.id %}
            <a href="{% url 'edit-comment' comment.pk %}">(Edit)</a>
          {% endif %}
        {% endif %}

        <br/><br/>
        
    {% endif %}
  {% endfor %}
  
  {% if user.profile.role != "end_user" %}
    <a href="{% url 'add_comment' post.pk %}">Add comment</a>
  {% endif %}
{% endif %}
<hr>


<br/>
<br/>

{% endblock %}

blog/templates/categories.html
{% extends 'base.html' %}

{% block content %}

{% if category_posts %}

<H1>{{ cats }}</H1>

<ul>
{% for post in category_posts %}
<li><a href="{% url 'article-detail' post.pk %}">{{ post.title }}</a> 
     -
      {{ post.author.first_name }}
      {{ post.author.last_name }} - 
      {{ post.post_date }} <small>
      
      {% if user.is_staff %}
        {% if user.id == post.author.id %}
          - <a href="{% url 'update_post' post.pk %}">(Edit)</a>
          <a href="{% url 'delete_post' post.pk %}">(Delete)</a>
        {% endif %}
      {% endif %}
      
      </small> <br/>
  {{ post.body|slice:":200"|safe }}</li>
{% endfor %}
</ul>

{% else %}
    <h2>There are, currently, no posts in this category.</h2>
{% endif %}

{% endblock %}

blog/templates/reset-pass.html
{% extends 'base.html' %} 
{% block title %}Reset Password{% endblock %} 
{% block content %}

<h1>Set New Password</h1>
<form method="POST" action="{% url 'reset-password' email %}">
    {% csrf_token %}

    <input type="text" style="display: none" name="email" value="{{ email }}" />

    <div>
        <label for="id_password">New Password:</label>
        <input type="password" name="password" id="id_password" class="form-control" />
    </div>

    <div>
        <label for="id_confirm_password">Confirm Password:</label>
        <input
            type="password"
            name="confirm_password"
            id="id_confirm_password" class="form-control"
        />
    </div>

    <button class="mt-2 btn btn-success float-end" type="submit">Reset Password</button>

    {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
</form>

{% endblock %}